//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadmeDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class secretaria
    {
        public int rol { get; set; }
        public string Usuario { get; set; }
        public string clave { get; set; }
        public long id { get; set; }
    }
}
