//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadmeDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usados041
    {
        public string cod_emp { get; set; }
        public string nom_emp { get; set; }
        public string rep_emp { get; set; }
        public string ruc_emp { get; set; }
        public string ciu_emp { get; set; }
        public string dir_emp { get; set; }
        public string tel_emp { get; set; }
        public string mar_chasis { get; set; }
        public string mode_chasis { get; set; }
        public string anio_chasis { get; set; }
        public string vin_chasis { get; set; }
        public string serie_motor_chasis { get; set; }
        public string mar_carr { get; set; }
        public string mod_carr { get; set; }
        public string anio_carr { get; set; }
        public string operadora { get; set; }
        public string num_asie_carr { get; set; }
        public string esta_carr { get; set; }
        public string tip_serv_carr { get; set; }
        public string propietario { get; set; }
        public string ced_pro { get; set; }
        public string ope1 { get; set; }
        public string disco_ope { get; set; }
        public string prov_matri_ope { get; set; }
        public string fec_rev_est { get; set; }
        public string fec_env_est { get; set; }
        public string responsable { get; set; }
        public string fec_rev_ter { get; set; }
        public string fec_env_ter { get; set; }
        public string res_res { get; set; }
        public string num_ord1 { get; set; }
        public string valor_pagar { get; set; }
        public string num_fact1 { get; set; }
        public string pago_terminado { get; set; }
        public string forma_pago1 { get; set; }
        public string mes_fact { get; set; }
        public string valor_pagar2 { get; set; }
        public string observacion { get; set; }
        public string deb_env { get; set; }
        public string accion_envio { get; set; }
        public string dias_pasados { get; set; }
        public long id { get; set; }
    }
}
